DustinCrawford.Web/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DustinCrawford.Web.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Missing()
        {
            Response.StatusCode = 404;
            return View();
        }

        public ActionResult Error()
        {
            Response.StatusCode = 500;
            return View();
        }
    }
}

DustinCrawford.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DustinCrawford.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Resume()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

    }
}

DustinCrawford.Web/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DustinCrawford.Web.Controllers
{
    public class NavigationController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

    }
}

DustinCrawford.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>

DustinCrawford.Web/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Title</title>
</head>
<body>
    <div class="panel panel-body">
        Hello, world!
    </div>
</body>
</html>

DustinCrawford.Web/Views/Navigation/About.cshtml
@{
    ViewBag.Title = "About";
    ViewBag.NavPage = "About";
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="box">
            <div class="row">
                <div class="col-lg-12">
                    <hr />
                       <h2 class="intro-text text-center"><strong> Resume Download</strong></h2>
                    <hr />
                    <div class="center-block text-center">
                        <i class="fa fa-file-pdf-o"></i><a href="~/Content/Documents/DustinCrawfordResume.pdf"><strong> Dustin Crawford - Resume - Updated 02/25/16</strong></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="box">
            <div class="col-lg-12">
                <hr>
                    <h2 class="intro-text text-center"><strong>Work History</strong></h2>
                <hr>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <p><strong><br />ZirMed, Inc.</strong></p>
                    <p><u>IT Intern</u> - Spring 2016</p>
                    <p>- Utilized latest MVC practices to develop a database health monitoring system for internal use by database administrators and other interested parties within the DevOps team</p>
                    <p>- Focused on domain-driven and test-driven design to ensure a stable, flexible codebase that is highly extensible and easily understood</p>
                    <p>- Used the Agile System Development Life Cycle while working in a five-man team to design and implement new features to the application in an iterative manner</p>
                    <p>- Developed an understanding of Object Relational Mapping as a data access pattern using nHibernate and Linq</p>
                    <p>- Released software using a proprietary, multi-environment deployment system</p>
                </div>
            </div>
            <div class="row">
                <hr>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <p><strong>ZirMed, Inc.</strong></p>
                    <p><u>Intern</u> - Summer 2015</p>
                    <p>- Worked with .NET Engineers to provide proper documentation for mapping customer files to requested patient statement format</p>
                    <p>- Spoke to clients over the phone to discuss options for formatting and layout of patient statements, and then delivered on client’s chosen options</p>
                    <p>- Provided quality assurance to clients via self-audit of changes to statement formats, as well as periodical peer-reviews of changes made</p>
                    <p>- Attended daily stand-up meetings to discuss with the rest of the Print Services team about widespread issues effecting multiple clients, and how to best tackle said issues</p>
                </div>
            </div>
        </div>
        <div class="box">
            <div class="col-lg-12">
                <hr>
                    <h2 class="intro-text text-center"><strong>Education</strong></h2>
                <hr>
            </div>
            <div class="row">
                <div class="col-md-7 col-md-offset-1">
                    <p><strong><br />Bachelor of Science - Computer Science</strong></p>
                    <p>University of Southern Indiana - Evansville, Indiana 47712</p>
                </div>
                <div class="col-md-3">
                    <br />
                    <p class="text-right">December 2015</p>
                </div>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr />
                    <h2 class="intro-text text-center"><strong>Projects</strong></h2>
                    <hr />
                </div>
                <div class="row">
                    <div class="col-md-11 col-md-offset-1">
                        <h2 class="text-left">
                            <a href="#"><br /><u>@Html.ActionLink("Collectible Card Game", "Projects", null, new { @id = "titleLink-inline" })</u></a>
                        </h2>
                    </div>
                    <div class="col-lg-10 col-lg-offset-1">
                        <br />
                        <p>This collectible card game, dubbed Immortia by my group, was designed and built in response to business requirements put forward by our CS483 professor. He served as our primary stakeholder in the endeavor and helped guide us through the entire life cycle of the project.</p>
                        <p>At the end of the Spring 2015 term, we presented this project to the Information Technology Alliance of Evansville, Indiana. This group of individuals is comprised of CEOs and CTOs of major businesses in the Evansville area.</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-11 col-md-offset-1">
                        <h2 class="text-left">
                            <a href="#"><u>@Html.ActionLink("Endless Runner Game", "Projects", null, new { @id = "titleLink-inline" })</u></a>
                        </h2>
                    </div>
                    <div class="col-lg-10 col-lg-offset-1">
                        <br />
                        <p>This runner game has no official name, but was called "RuNinja" by the small team that created it. Inspired by other runner games such as Temple Run&trade; and Robot Unicorn Attack&trade;, this game was primarily designed for mobile devices and will be available on both major device platforms very soon.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

DustinCrawford.Web/Views/Navigation/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    ViewBag.NavPage = "Contact";
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";
}


<div class="container">
    <div class="box">
        <div class="row">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center"><strong>Contact</strong></h2>
                <hr>
            </div> 
        </div>
        <div class="row">
            <div class="text-center">
                <i class="fa fa-mobile"></i>
                Phone: 502-356-2489
            </div>
        </div>
        <div class="row">
            <div class="text-center">
                <i class="fa fa-envelope"></i>
                E-mail: <a href="mailto:dustindjc92@gmail.com">dustindjc92@gmail.com</a>
            </div>
        </div>
        <div class="row">
            <div class="text-center">
                <i class="fa fa-linkedin"></i>
                LinkedIn: <a href="https://www.linkedin.com/in/dustin-crawford-00072186">Dustin J Crawford</a>
            </div>
        </div>
    </div>
</div>

DustinCrawford.Web/Views/Navigation/Home.cshtml
@{
    ViewBag.Title = "Home";
    ViewBag.NavPage = "Home";
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title>Home</title>
</head>
<body>
    <div class="container">
        <div class="box">
            <div class="row">
                <div class="col-lg-12">
                    <hr />
                        <h2 class="title-text text-center">Home</h2>
                    <hr />
                </div>
            </div>
            <div class="row">
                <p class="text-center">Software developer by day, game development hobbyist and enthusiast by night.</p>
                <br />
            </div>
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-left">
                    <p>I am a junior-level software developer currently working as an IT Intern at ZirMed, Inc. and based in Louisville, Kentucky. My goal as a professional is to continuously further my knowledge of the many different software development methodologies, and to then utilize my knowledge of these methodologies along with both domain-driven and test-driven design to effectively and efficiently develop flexible real-world applications.</p>
                    <br />
                    <p>With experience in developing small-scale applications in C# and the .NET framework, I am currently broadening my skillset by assisting in the development of much larger-scale applications at ZirMed. It is my first real endeavor into developing real-world applications.</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

DustinCrawford.Web/Views/Navigation/Projects.cshtml
@{
    ViewBag.Title = "Projects";
    ViewBag.NavPage = "Projects";
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";
}


<div class="container">
    <div class="box">
        <hr />
            <h4 class="intro-text text-center"><strong>Personal/Educational Projects</strong></h4>
        <hr />

        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h2 class="text-left">
                    <strong><u>Collectible Card Game - "Immortia"</u></strong>
                </h2>
            </div>
            <div class="col-lg-10 col-lg-offset-1">
                <br />
                <p>This game was developed by myself and a group of five other junior/senior level computer science majors at the University of Southern Indiana. It was completed for the CS483 requirement of the BSc in Computer Science, and took around 4 months to complete from concept to final demo.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-left">
                <p>&bull; Utilized an agile methodology to quickly implement and iterate upon new features</p>
                <p>&bull; Developed using the C# language along with the <i>Unity</i> game engine</p>
                <p>&bull; Presented our work to the Information Technology Alliance of Evansville, Indiana in May 2015</p>
                <p>&bull; Inspired heavily by Hearthstone&trade;, which is developed by Blizzard Entertainment</p>
                <br />
                <br />
            </div>
        </div>
        <div class="row">
            <img src="~/Content/Images/Immortia_WIP_6.png" class="col-lg-5 col-lg-offset-1 img-responsive img-thumbnail"/>
            <img src="~/Content/Images/Immortia_WIP_7.png" class="col-lg-5 img-responsive img-thumbnail"/>
        </div>
        <div class="row col-md-offset-1">
            <br />
            <p>The source code for this game can be viewed <a href="https://bitbucket.org/DustinJCrawford/immortia/src">here</a> on BitBucket</p>
        </div>

        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                <h2 class="text-left">
                    <br />
                    <br />
                    <strong><u>Endless Runner Game - "RuNinja"</u></strong>
                </h2>
            </div>
            <div class="col-lg-10 col-lg-offset-1">
                <br />
                <p>This game was developed primarily by myself with some assistance from a few fellow students at the University of Southern Indiana, and was completed to fulfill the CS499 requirement. </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-left">
                <p>&bull; Developed using the C# language along with the <i>Unity</i> game engine</p>
                <p>&bull; Created with the design goal of "Easy to learn but hard to master" in mind</p>
                <p>&bull; Inspired by other endless runner games such as Temple Run&trade; and Robot Unicorn Attack&trade;</p>
                <br />
                <br />
            </div>
        </div>

        <div class="row">
            <img src="~/Content/Images/runner_screen_1.png" class="col-lg-5 col-lg-offset-1 img-responsive img-thumbnail" />
            <img src="~/Content/Images/runner_screen_2.png" class="col-lg-5 img-responsive img-thumbnail" />
        </div>
        <div class="row col-md-offset-1">
            <br />
            <p>The source code for this game can be viewed <a href="https://bitbucket.org/DustinJCrawford/android-project/src">here</a> on BitBucket</p>
            <p>Available on Google Play and Apple Store soon!</p>
        </div>
    </div>
</div>

DustinCrawford.Web/Views/Navigation/Resume.cshtml
@{
    ViewBag.Title = "Resume";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/business-casual.css" rel="stylesheet" />
<link href="~/Content/linkStyle.css" rel="stylesheet" />

<div class="container-fluid">

    <div class="panel panel-default">
        <div class="panel panel-heading"><h4>Resume (PDF Format)</h4></div>
        <div class="panel panel-body">
            <div class="center-block">
                <a href="~/Content/DustinCrawfordResume.pdf">Dustin Crawford - Resume - Updated 08/09/15</a>
            </div>
        </div>
    </div>

</div>

<!--jQuery-->
<script src="~/Scripts/jquery-2.2.0.js"></script>
<!--Bootstrap-->
<script src="~/Scripts/bootstrap.min.js"></script>

DustinCrawford.Web/Views/Shared/Error404.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ERROR 404</title>
</head>
<body>
    <div> 
        <h1>ERROR</h1>
    </div>
</body>
</html>

DustinCrawford.Web/Views/Shared/Layouts/_Footer.cshtml
@{
    Layout = null;
}

@Styles.Render("~/bundles/facss")
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <a href="https://www.linkedin.com/in/dustin-crawford-00072186" value="LinkedIn">
                    <i class="fa fa-linkedin-square fa-2x"></i>
                </a>
                <a href="http://www.bitbucket.org/DustinJCrawford" value="BitBucket">
                    <i class="fa fa-bitbucket-square fa-2x"></i>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="text-center col-lg-12">Copyright &copy; 2016 - Dustin Crawford</div>
        </div>
    </div>
</footer>

DustinCrawford.Web/Views/Shared/Layouts/_GA.cshtml
@{
    Layout = null;
}

<!--Google Analytics-->
<script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-72497822-1', 'auto');
        ga('send', 'pageview');

</script>

DustinCrawford.Web/Views/Shared/Layouts/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/bundles/bootstrapcss")
    @Styles.Render("~/bundles/facss")
    @Styles.Render("~/bundles/localstyles")
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <title>Dustin J Crawford</title>
</head>
<body>
    
    @Html.Partial("Layouts/_NavBar")

    @RenderBody()

    @Html.Partial("Layouts/_Footer")
    @Html.Partial("Layouts/_GA")

    @Styles.Render("~/bundles/bootstrapjs")
    @Styles.Render("~/bundles/jquery")
</body>
</html>

DustinCrawford.Web/Views/Shared/Layouts/_NavBar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<div class="brand"><a id="titleLink-header" href="http://www.dustinjcrawford.com">Dustin J Crawford</a></div>
<div class="address-bar">204 Saddleback Drive | Charlestown, IN 47111 | 502.356.2489</div>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li @if (ViewBag.NavPage == "Home") { @: class="active"
                                                                        }>
                    @Html.ActionLink("Home", "Home", "Navigation")
                </li>

                <li @if (ViewBag.NavPage == "About") { @: class="active"
                                                                        }>
                    @Html.ActionLink("About", "About", "Navigation")
                </li>

                <li @if (ViewBag.NavPage == "Projects") { @: class="active"
                                                                                                }>
                    @Html.ActionLink("Projects", "Projects", "Navigation")
                </li>

                <li @if (ViewBag.NavPage == "Contact") { @: class="active"
                                                                        }>
                    @Html.ActionLink("Contact", "Contact", "Navigation")
                </li>
            </ul>
        </div>
    </div>
</nav>